- name: Deploy backend to Azure App Service 
  hosts: localhost
  connection: local

  tasks:
    - name: Deploy ZIP Package using Azure CLI
      command: >
        az webapp deploy 
        --resource-group multi-tier-rg
        --name multitier-backend-app
        --src-path "C:/Windows/System32/Azure-Multi-Tier-App/backend.zip"
